version: '2'
services:
  aggregator:
    container_name: aggregator
    build:
      context: ./aggregator/docker/
    env_file: ./aggregator/docker-env.list
    environment:
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka

  kafka:
    container_name: kafka
    image: ches/kafka:0.10.1.0
    ports:
     - "9092:9092"
    environment:
      ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper
    image: jplock/zookeeper:3.4.8
    ports:
     - "2181:2181"