check:
    global:
        statements: 90
        lines: 90
        branches: 90
        functions: 80
        excludes: []
    each:
        statements: 90
        lines: 90
        branches: 90
        functions: 80
        excludes: []